name: CD

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.11.0
        with:
          minikube version: 'v1.33.0'
          kubernetes version: 'v1.30.0' 

      - name: Start Minikube
        run: |
          minikube delete
          minikube start --driver=docker

      - name: Configure kubectl
        uses: steebchen/kubectl@v2.0.0
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kubectl in Minikube
        run: minikube kubectl -- get nodes

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker images
        run: |
          docker pull ervincaravaliibarra/galeria-20
          docker pull ervincaravaliibarra/bdgaleria-20

      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace backend 
          kubectl apply -f .github/manifests/configmap.yaml -n backend
          kubectl apply -f .github/manifests/db-deployment.yaml -n backend
          kubectl apply -f .github/manifests/web-deployment.yaml -n backend
          kubectl apply -f .github/manifests/web-service.yaml -n backend
          sleep 90 

      - name: Get deployed resources
        run: |
          kubectl get all -n backend
          kubectl port-forward svc/web-service 3120:3120 -n backend

